### ISSUE TITLE
`KeyError: 'distance'` with Whistle Fit

### ISSUE THREAD

**Issue by jhansche** [RobertD502/home-assistant-whistle#10]
After the recent update to support Whistle Fit (see #7), everything seems to be working great (thank you!)

But just today I noticed this error appearing in the logs. It still seems to be working well despite this error. I know occasional logs are to be expected, but seeing the number of times this one is happening (327 times in 2 days), I thought it best to at least put it out there, just in case.

```
This error originated from a custom integration.

Logger: homeassistant
Source: custom_components/whistle/sensor.py:1144
Integration: Whistle (documentation, issues)
First occurred: September 12, 2022 at 8:26:28 PM (327 occurrences)
Last logged: 9:52:32 PM

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 151, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 283, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 110, in async_update_listeners
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 348, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 533, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 571, in _async_write_ha_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 539, in _stringify_state
    if (state := self.state) is None:
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 388, in state
    value = self.native_value
  File "/config/custom_components/whistle/sensor.py", line 1144, in native_value
    return self.pet_data.events['daily_items'][00]['data']['distance']
KeyError: 'distance'
```

**Comment by RobertD502** [comment]
This is fixed in 0.1.3 that I released earlier today. Some events don't have associated distances or calories.

**Comment by jhansche** [comment]
I literally just went through hacs and saw the update, and the release notes... 😳 Was coming back here to close as already fixed. My mistake!

**Comment by RobertD502** [comment]
I realized events about a pet hitting their goal also don't have a duration key returned. Update to `0.1.4` to also prevent seeing a KeyError with this type of scenario.
