### ISSUE TITLE
Sensors Appearing After Install

### ISSUE THREAD

**Issue by five2seven** [RobertD502/home-assistant-whistle#2]
I see the "last activity" sensor but nothing else related to Whistle. This is what I'm seeing in the logs: 

`Logger: homeassistant.components.device_tracker
Source: custom_components/whistle/device_tracker.py:73 
Integration: Device tracker 
First occurred: 10:21:57 PM (1 occurrences) 
Last logged: 10:21:57 PM

Error while setting up whistle platform for device_tracker
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/whistle/device_tracker.py", line 50, in async_setup_entry
    pets.append(WhistleTracker(pet, whistle))
  File "/config/custom_components/whistle/device_tracker.py", line 66, in __init__
    self._pet_update(pet)
  File "/config/custom_components/whistle/device_tracker.py", line 73, in _pet_update
    self._latitude = pet['last_location']['latitude']
TypeError: 'NoneType' object is not subscriptable`

**Comment by RobertD502** [comment]
If you restart home assistant, does this error occur again or was it a one-off situation?

**Comment by five2seven** [comment]
I didn’t realize you responded to this, I’m sorry! Nothing ever changed, I’ve only seen that one sensor for the past few months since installing. I just updated to the newer release but still just the last activity. I guess it’s because I have the old Whistle and maybe that’s all it exposes to the API. Oh well, thanks for the great work!

**Comment by RobertD502** [comment]
@five2seven what whistle model do you have?

**Comment by five2seven** [comment]
I have a Whistle Fit but it looks like they have come out with a newer version that requires a subscription plan. Mine does not. This is what it says in the iOS app for me. 
![DD9CD8B8-864B-41D5-ADEC-917EC4C9401B](https://user-images.githubusercontent.com/44069152/151688865-dfd0421a-3275-44a8-80d9-52d55fdf2e0f.jpeg)

**Comment by RobertD502** [comment]
The Whistle Fit lacks GPS which is why that is being logged - the fit doesn't have any coordinates to provide.
